#
# This source file is part of the Apodini open source project
#
# SPDX-FileCopyrightText: 2021 Paul Schmiedmayer and the project authors (see CONTRIBUTORS.md) <paul.schmiedmayer@tum.de>
#
# SPDX-License-Identifier: MIT
#

name: Build and Test

on:
  workflow_call:
    inputs:
      packagename:
        description: 'Name of the package passed to Xcode on macOS builds. Required for generating a test coverage or testing the DoC documentation generation'
        required: true
        type: string
      path:
        description: 'The path where the Swift Package is located. Defaults to $GITHUB_WORKSPACE'
        required: false
        type: string
        default: '.'
      testdocc:
        description: 'A flag indicating if the DocC documentation building should be tested'
        required: false
        type: boolean
        default: true
      aptgetdependencies:
        description: 'Dependencies that must be installed using apt-get before builds on Ubuntu'
        required: false
        type: string
      yumdependencies:
        description: 'Dependencies that must be installed using yum before builds on Amazon Linux and CentOS'
        required: false
        type: string

jobs:
  macos:
    name: macOS ${{ matrix.configuration }}
    runs-on: macos-11
    strategy:
      fail-fast: false
      matrix:
        configuration: [debug, release, release_testing]
    defaults:
      run:
        working-directory: ${{ inputs.path }}
    steps:
    - uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1.4.0
      with:
        xcode-version: latest
    - uses: actions/cache@v2
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
    - name: Check Environment
      run: |
          xcodebuild -version
          swift --version
          echo "inputs.packagename: ${{ inputs.packagename }}"
          echo "inputs.path: ${{ inputs.path }}"
          echo "inputs.testdocc: ${{ inputs.testdocc }}"
          echo "matrix.configuration: ${{ matrix.configuration }}"
    - name: Release Build
      if: matrix.configuration == 'release'
      run: swift build -c release
    - name: Release Build & Test
      if: matrix.configuration == 'release_testing'
      run: swift test -c release -Xswiftc -enable-testing -Xswiftc -DRELEASE_TESTING -Xlinker -rpath -Xlinker "$(xcode-select -p)/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.5/macosx"
    - name: Debug Build & Test
      if: matrix.configuration == 'debug'
      run: swift test -c debug --enable-code-coverage -Xswiftc -DCOVERAGE -Xlinker -rpath -Xlinker "$(xcode-select -p)/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.5/macosx"
    - name: Convert coverage report
      if: matrix.configuration == 'debug'
      run: xcrun llvm-cov export -format="lcov" .build/debug/${{ inputs.packagename }}PackageTests.xctest/Contents/MacOS/${{ inputs.packagename }}PackageTests -instr-profile .build/debug/codecov/default.profdata > coverage.lcov
    - name: Upload coverage to Codecov
      if: matrix.configuration == 'debug'
      uses: codecov/codecov-action@v2
    - name: Test Generating Docs
      if: matrix.configuration == 'debug' && inputs.testdocc == true
      run: |
          xcodebuild docbuild -scheme ${{ inputs.packagename }} -destination platform=macOS -derivedDataPath ./.xcodebuild
          cp -r $(find ./.xcodebuild -type d -name '${{ inputs.packagename }}.doccarchive') ./${{ inputs.packagename }}.doccarchive
          echo "The DocC archive can be found at ./${{ inputs.packagename }}.doccarchive"
  linux:
    name: Linux ${{ matrix.linux }} ${{ matrix.configuration }}
    container:
      image: swift:${{ matrix.linux }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        linux: [bionic, focal, amazonlinux2, centos8]
        configuration: [debug, release, release_testing]
    defaults:
      run:
        working-directory: ${{ inputs.path }}
    steps:
    - uses: actions/checkout@v2
    - name: Check Environment
      run: |
          swift --version
          echo "inputs.packagename: ${{ inputs.packagename }}"
          echo "inputs.path: ${{ inputs.path }}"
          echo "inputs.aptgetdependencies: ${{ inputs.aptgetdependencies }}"
          echo "inputs.yumdependencies: ${{ inputs.yumdependencies }}"
          echo "matrix.linux: ${{ matrix.linux }}"
          echo "matrix.configuration: ${{ matrix.configuration }}"
    - name: Install apt-get Dependencies
      if: matrix.linux != 'centos8' && matrix.linux != 'amazonlinux2' && inputs.aptgetdependencies != ''
      run: apt-get update && apt-get install -y --no-install-recommends ${{ inputs.aptgetdependencies }}
    - name: Install yum Dependencies
      if: matrix.linux == 'amazonlinux2' && inputs.yumdependencies != ''
      run: yum update -y && yum install -y ${{ inputs.yumdependencies }}
    - name: Install yum Dependencies
      if: matrix.linux == 'centos8' && inputs.yumdependencies != ''
      run: yum update -y --nobest && yum install -y ${{ inputs.yumdependencies }}
    - uses: actions/cache@v2
      with:
        path: .build
        key: ${{ runner.os }}-${{matrix.linux}}-spm-${{ hashFiles('Package.resolved') }}
    - name: Check Swift version
      run: swift --version
    - name: Release Build
      if: matrix.configuration == 'release'
      run: swift build -c release
    - name: Release Build & Test
      if: matrix.configuration == 'release_testing'
      run: swift test -c release -Xswiftc -enable-testing -Xswiftc -DRELEASE_TESTING
    - name: Debug Build & Test
      if: matrix.configuration == 'debug'
      run: swift test -c debug
