#
# This source file is part of the Apodini open source project
#
# SPDX-FileCopyrightText: 2021 Paul Schmiedmayer and the project authors (see CONTRIBUTORS.md) <paul.schmiedmayer@tum.de>
#
# SPDX-License-Identifier: MIT
#

name: Generate Docs

on:
  workflow_call:
    inputs:
      targetname:
        description: 'Name of the target that the documentation should be build of'
        required: true
        type: string

jobs:
  macos:
    name: Generate Docs
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest
    - uses: actions/cache@v2
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
    - name: Check Environment
      run: |
          xcodebuild -version
          swift --version
          echo "inputs.targetname: ${{ inputs.targetname }}"
          echo "github.event.repository.name: ${{ github.event.repository.name }}"
    - name: Generate Documentation
      run: |
          swift package --allow-writing-to-directory ./docs \
            generate-documentation --target ${{ inputs.targetname }} \
            --disable-indexing \
            --transform-for-static-hosting \
            --hosting-base-path ${{ github.event.repository.name }} \
            --output-path ./docs
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ github.token }}
        publish_dir: ./docs
        force_orphan: true