#
# This source file is part of the Apodini open source project
#
# SPDX-FileCopyrightText: 2021 Paul Schmiedmayer and the project authors (see CONTRIBUTORS.md) <paul.schmiedmayer@tum.de>
#
# SPDX-License-Identifier: MIT
#

name: Swift Package Update

on:
  workflow_call:
    inputs:
      author:
        description: 'The author of the resulting PR containing the updated Swift package'
        required: false
        type: string
        default: ApodiniBot
      reviewers:
        description: 'The reviewers of the resulting pull request containing the updated Swift package'
        required: false
        type: string
        default: PSchmiedmayer
      branch:
        description: 'The branch that should be used to create the pull request'
        required: false
        type: string
        default: bots/update-dependencies
    secrets:
      token:
        description: 'The Personal Access Token with permissions to push to the repository. Using the GITHUB_TOKEN does not trigger GitHub Actions in the resulting pull request.'
        required: true
  
jobs:
  createPR:
    name: Create Pull Request
    container:
      image: swift:latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check Swift version
      run: swift --version
    - name: Update Swift Packages
      run: swift package update
    - uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.token }}
        commit-message: Update dependencies
        title: Update dependencies
        body: Update the Swift Package dependencies.
        delete-branch: true
        base: develop
        branch: bots/update-dependencies
        assignees: ${{ inputs.author }}
        committer: ${{ inputs.author }} <${{ inputs.author }}@users.noreply.github.com>
        author: ${{ inputs.author }} <${{ inputs.author }}@users.noreply.github.com>
        reviewers: ${{ inputs.reviewers }}
